import type { ProjectFile } from '../types.js';
import type { LayoutEngineSettings, LayoutFileMetrics } from './types.js';

export function createLayoutFileMetrics(
  file: ProjectFile,
  settings: LayoutEngineSettings,
  rootNodeId: string | undefined,
  originOffset: { x: number; y: number },
  overrides: Partial<LayoutFileMetrics> = {},
): LayoutFileMetrics {
  return {
    fileId: file.id,
    filePath: file.path,
    rootNodeId,
    originOffset,
    positionedNodes: 0,
    translatedNodes: 0,
    normalizedNodes: 0,
    xNormalizedNodes: 0,
    yNormalizedNodes: 0,
    horizontalGap: settings.horizontalGap,
    verticalGap: settings.verticalGap,
    dagLevels: 0,
    dagEffectiveVerticalGap: 0,
    dagSafetyPasses: 0,
    treeNodes: 0,
    treeRoots: 0,
    treeMaxDepth: 0,
    forks: 0,
    branchClusters: 0,
    semanticFlowEdges: 0,
    semanticAttachmentEdges: 0,
    semanticOrderedAttachmentEdges: 0,
    semanticStructuralEdges: 0,
    semanticFlowForks: 0,
    semanticStructuralForks: 0,
    semanticMixedParents: 0,
    semanticAttachmentFamilies: 0,
    singleChildParents: 0,
    laneSnaps: 0,
    connectionPlanesAligned: 0,
    portAlignmentFallbacks: 0,
    authorDepthBands: 0,
    deepBranchStarts: 0,
    authorDepthXRescues: 0,
    contourXRescues: 0,
    attachmentXAdjustments: 0,
    maxAttachmentXAdjustment: 0,
    attachmentContourRescues: 0,
    attachmentContourShiftedNodes: 0,
    maxAttachmentContourShift: 0,
    routedFlowEdges: 0,
    edgeNodeIntersectionsBefore: 0,
    edgeNodeIntersectionsAfter: 0,
    edgeNodeCorridorIntrusionsAfter: 0,
    edgeEdgeCrossingsAfter: 0,
    attachmentEdgeNodeIntersectionsAfter: 0,
    edgeCorridorRepairs: 0,
    edgeCorridorShiftedNodes: 0,
    maxEdgeCorridorShift: 0,
    flowLanes: 0,
    flowLaneEdges: 0,
    laneRealignments: 0,
    laneRealignedNodes: 0,
    laneNormalizationBlocked: 0,
    visualRowEdges: 0,
    visualRowAuthorJitterEdges: 0,
    visualRowMisalignedBefore: 0,
    visualRowMisalignedAfter: 0,
    visualRowRealignments: 0,
    maxVisualRowDeviationBefore: 0,
    maxVisualRowDeviationAfter: 0,
    visualGroups: 0,
    flowVisualGroups: 0,
    chainRows: 0,
    chainRowEdges: 0,
    authorRowGuides: 0,
    authorColumnGuides: 0,
    chainRowsMisalignedBefore: 0,
    chainRowsMisalignedAfter: 0,
    rowGuidesAlignedBefore: 0,
    rowGuidesAlignedAfter: 0,
    columnGuidesAlignedBefore: 0,
    columnGuidesAlignedAfter: 0,
    chainRowRealignments: 0,
    rowGuideRealignments: 0,
    columnGuideRealignments: 0,
    authorGridMovedNodes: 0,
    authorGridBlocked: 0,
    maxAuthorGridShiftX: 0,
    maxAuthorGridShiftY: 0,
    maxRowGuideDeviationBefore: 0,
    maxRowGuideDeviationAfter: 0,
    maxColumnGuideDeviationBefore: 0,
    maxColumnGuideDeviationAfter: 0,
    attachmentPixelRows: 0,
    attachmentPixelRowsMisalignedBefore: 0,
    attachmentPixelRowsMisalignedAfter: 0,
    orderedAttachmentColumns: 0,
    orderedAttachmentColumnsMisalignedBefore: 0,
    orderedAttachmentColumnsMisalignedAfter: 0,
    pixelAlignmentRealignments: 0,
    pixelAlignmentBlocked: 0,
    maxPixelAlignmentShiftX: 0,
    maxPixelAlignmentShiftY: 0,
    maxLaneShift: 0,
    maxConnectionPlaneDeviationBefore: 0,
    medianConnectionPlaneDeviationBefore: 0,
    maxConnectionPlaneDeviationAfter: 0,
    medianConnectionPlaneDeviationAfter: 0,
    xRescueShiftedNodes: 0,
    maxXRescueShift: 0,
    clusterCollisionsResolved: 0,
    clusterShiftedNodes: 0,
    maxClusterShift: 0,
    xSpanBefore: 0,
    xSpanAfter: 0,
    ySpanBefore: 0,
    ySpanAfter: 0,
    translatedComments: 0,
    translatedGroups: 0,
    resizedGroups: 0,
    nodeOverlapsBefore: 0,
    nodeOverlapsAfter: 0,
    floaterMode: settings.floaterMode,
    floatingNodes: 0,
    floatersHandled: 0,
    floaterOverlapsBefore: 0,
    floaterOverlapsAfter: 0,
    groupOverlapsBefore: 0,
    groupOverlapsAfter: 0,
    newGroupOverlaps: [],
    groupMembershipByBounds: 0,
    groupMembershipByCenter: 0,
    groupMembershipAmbiguous: 0,
    groupParentAmbiguous: 0,
    groupAnchorRescues: 0,
    groupAnchorRescuedNodes: 0,
    blockReasons: [],
    warnings: [],
    blocked: false,
    ...overrides,
  };
}

export interface LayoutQualitySummary {
  blocked: boolean;
  nodeOverlaps: number;
  flowEdgeNodeIntersections: number;
  attachmentEdgeNodeIntersections: number;
  unrelatedCrossings: number;
}

/** Small stable quality surface; detailed metrics remain diagnostics-only. */
export function summarizeLayoutQuality(metrics: LayoutFileMetrics): LayoutQualitySummary {
  return {
    blocked: metrics.blocked,
    nodeOverlaps: metrics.nodeOverlapsAfter,
    flowEdgeNodeIntersections: metrics.edgeNodeIntersectionsAfter,
    attachmentEdgeNodeIntersections: metrics.attachmentEdgeNodeIntersectionsAfter,
    unrelatedCrossings: metrics.edgeEdgeCrossingsAfter,
  };
}
